config/routes.rb
Rails.application.routes.draw do
  root "tweet_streams#new"
  resources :tweet_streams, only: [:new, :create]
end

app/models/twitter_client.rb
class TwitterClient
  attr_reader :client

  def initialize(client = TWITTER)
    @client = client
  end

  def fetch_tweets(twitter_handle)
    client.user_timeline(twitter_handle)
  end

  def self.fetch_tweets(twitter_handle)
    TWITTER.user_timeline(twitter_handle)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweet_streams_controller.rb
class TweetStreamsController < ApplicationController
  attr_accessor :twitter_client

  def new
  end

  def create
    @tweets = twitter_client.fetch_tweets(params[:twitter_handle])
  end

  def twitter_client
    @twitter_client ||= TwitterClient.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweet_streams/create.html.erb
<div>
  <ul>
    <% @tweets.each do |tweet| %>
    <li class="tweet">
      <p><em><%= tweet.user.screen_name %></em> says: <%= tweet.text %></p>
    </li>
    <% end %>
  </ul>
</div>

<p>
  <%= link_to("try another user", new_tweet_stream_path) %>
</p>

app/views/tweet_streams/new.html.erb
<%= form_tag(tweet_streams_path) do %>
  <%= label_tag "enter twitter handle" %>
  <%= text_field_tag("twitter_handle")  %>
  <%= submit_tag "show tweets" %>
<% end %>